export const products = [
  {
    id: 1,
    name: "Eco Storage Container",
    slug: "eco-storage-container",
    price: 24.99,
    description: "Sustainable storage solution for your kitchen and home.",
    fullDescription:
      "Our Eco Storage Containers are made from recycled materials and designed to last. Perfect for storing food, organizing small items, or keeping your home tidy. These containers are microwave and dishwasher safe, making them practical for everyday use.",
    specifications: [
      "Made from 100% recycled plastic",
      "BPA-free and food safe",
      "Microwave and dishwasher safe",
      "Stackable design for easy storage",
      "Available in multiple sizes",
      "Airtight seal to keep food fresh",
    ],
    image: "/sustainable-kitchen-storage.png",
    images: [
      "/sustainable-kitchen-storage.png",
      "/open-eco-container.png",
      "/stacked-eco-containers.png",
      "/sustainable-kitchen-storage.png",
    ],
    isNew: true,
    isSale: false,
    stockStatus: "in_stock",
    sku: "ESC-001",
    bulkPricing: true,
  },
  {
    id: 2,
    name: "Biodegradable Plant Pots",
    slug: "biodegradable-plant-pots",
    price: 12.99,
    description: "Eco-friendly pots that break down naturally in soil.",
    fullDescription:
      "Our Biodegradable Plant Pots are the perfect solution for environmentally conscious gardeners. Made from natural materials, these pots break down in the soil as your plants grow, eliminating the need for transplanting and reducing plastic waste. Ideal for seedlings and small plants.",
    specifications: [
      "100% biodegradable and compostable",
      "Made from plant-based materials",
      "Available in various sizes",
      "Naturally adds nutrients to soil as it breaks down",
      "Perfect for seedlings and transplanting",
      "Reduces transplant shock",
    ],
    image: "/seedling-nursery.png",
    images: [
      "/seedling-nursery.png",
      "/sprouting-sustainability.png",
      "/garden-biodegradable-pots.png",
      "/placeholder.svg?height=600&width=600&query=biodegradable+plant+pots+set",
    ],
    isNew: false,
    isSale: true,
    originalPrice: 19.99,
    stockStatus: "in_stock",
    sku: "BPP-002",
    bulkPricing: true,
  },
  {
    id: 3,
    name: "Recycled Plastic Chairs",
    slug: "recycled-plastic-chairs",
    price: 49.99,
    description: "Durable outdoor chairs made from recycled ocean plastic.",
    fullDescription:
      "Our Recycled Plastic Chairs are stylish, comfortable, and environmentally responsible. Made from plastic recovered from oceans and waterways, each chair helps reduce pollution while providing a durable seating solution for your outdoor spaces. Weather-resistant and easy to clean.",
    specifications: [
      "Made from 100% recycled ocean plastic",
      "UV-resistant - won't fade in sunlight",
      "Weather-proof and suitable for outdoor use",
      "Easy to clean with soap and water",
      "Stackable design for easy storage",
      "Available in multiple colors",
    ],
    image: "/colorful-recycled-chairs.png",
    images: [
      "/colorful-recycled-chairs.png",
      "/placeholder.svg?height=600&width=600&query=recycled+plastic+chairs+outdoor",
      "/placeholder.svg?height=600&width=600&query=recycled+plastic+chairs+stacked",
      "/placeholder.svg?height=600&width=600&query=recycled+plastic+chairs+set",
    ],
    isNew: false,
    isSale: false,
    stockStatus: "in_stock",
    sku: "RPC-003",
    bulkPricing: true,
  },
  {
    id: 4,
    name: "Eco-Friendly Water Bottles",
    slug: "eco-friendly-water-bottles",
    price: 14.99,
    description: "Reusable water bottles made from sustainable materials.",
    fullDescription:
      "Stay hydrated while reducing plastic waste with our Eco-Friendly Water Bottles. Made from sustainable materials, these bottles are durable, leak-proof, and perfect for everyday use. The insulated design keeps your drinks at the ideal temperature for hours, whether hot or cold.",
    specifications: [
      "Made from sustainable bamboo and stainless steel",
      "BPA-free and non-toxic",
      "Double-wall insulation keeps drinks hot or cold",
      "Leak-proof design",
      "24-hour cold retention, 12-hour hot retention",
      "Available in multiple colors and sizes",
    ],
    image: "/placeholder.svg?height=300&width=300&query=eco+friendly+water+bottles",
    images: [
      "/placeholder.svg?height=600&width=600&query=eco+friendly+water+bottles",
      "/placeholder.svg?height=600&width=600&query=eco+friendly+water+bottles+open",
      "/placeholder.svg?height=600&width=600&query=eco+friendly+water+bottles+lifestyle",
      "/placeholder.svg?height=600&width=600&query=eco+friendly+water+bottles+set",
    ],
    isNew: true,
    isSale: false,
  },
  {
    id: 5,
    name: "Compostable Food Containers",
    slug: "compostable-food-containers",
    price: 18.99,
    description: "Eco-friendly takeout containers that break down naturally.",
    fullDescription:
      "Our Compostable Food Containers are the perfect alternative to traditional plastic takeout containers. Made from plant-based materials, these containers break down completely in commercial composting facilities, leaving no microplastics behind. Ideal for restaurants, food trucks, and eco-conscious homes.",
    specifications: [
      "Made from plant-based materials",
      "100% compostable in commercial facilities",
      "Microwave and freezer safe",
      "Oil and water resistant",
      "Available in various sizes and shapes",
      "Breaks down within 90 days in proper composting conditions",
    ],
    image: "/placeholder.svg?height=300&width=300&query=compostable+food+containers",
    images: [
      "/placeholder.svg?height=600&width=600&query=compostable+food+containers",
      "/placeholder.svg?height=600&width=600&query=compostable+food+containers+with+food",
      "/placeholder.svg?height=600&width=600&query=compostable+food+containers+stacked",
      "/placeholder.svg?height=600&width=600&query=compostable+food+containers+set",
    ],
    isNew: false,
    isSale: true,
    originalPrice: 24.99,
  },
  {
    id: 6,
    name: "Reusable Shopping Bags",
    slug: "reusable-shopping-bags",
    price: 9.99,
    description: "Durable shopping bags made from recycled materials.",
    fullDescription:
      "Say goodbye to single-use plastic bags with our Reusable Shopping Bags. Made from recycled materials, these bags are strong enough to carry heavy groceries while being gentle on the environment. The compact design allows them to fold into a small pouch, making them easy to keep in your car or purse.",
    specifications: [
      "Made from recycled PET bottles",
      "Holds up to 40 pounds",
      "Folds into attached pouch for easy storage",
      "Machine washable",
      "Reinforced handles and stitching",
      "Available in various colors and patterns",
    ],
    image: "/placeholder.svg?height=300&width=300&query=reusable+shopping+bags",
    images: [
      "/placeholder.svg?height=600&width=600&query=reusable+shopping+bags",
      "/placeholder.svg?height=600&width=600&query=reusable+shopping+bags+folded",
      "/placeholder.svg?height=600&width=600&query=reusable+shopping+bags+with+groceries",
      "/placeholder.svg?height=600&width=600&query=reusable+shopping+bags+set",
    ],
    isNew: false,
    isSale: false,
  },
  {
    id: 7,
    name: "Bamboo Cutlery Set",
    slug: "bamboo-cutlery-set",
    price: 15.99,
    description: "Portable and sustainable alternative to plastic utensils.",
    fullDescription:
      "Our Bamboo Cutlery Set provides a sustainable alternative to single-use plastic utensils. Each set includes a fork, knife, spoon, and chopsticks, all made from naturally antibacterial bamboo. The included cotton pouch makes it easy to carry your utensils wherever you go, reducing plastic waste one meal at a time.",
    specifications: [
      "Made from sustainable bamboo",
      "Includes fork, knife, spoon, and chopsticks",
      "Comes with cotton carrying pouch",
      "Naturally antibacterial",
      "Lightweight and portable",
      "Hand wash recommended",
    ],
    image: "/placeholder.svg?height=300&width=300&query=bamboo+cutlery+set",
    images: [
      "/placeholder.svg?height=600&width=600&query=bamboo+cutlery+set",
      "/placeholder.svg?height=600&width=600&query=bamboo+cutlery+set+in+pouch",
      "/placeholder.svg?height=600&width=600&query=bamboo+cutlery+set+with+food",
      "/placeholder.svg?height=600&width=600&query=bamboo+cutlery+set+displayed",
    ],
    isNew: false,
    isSale: false,
  },
  {
    id: 8,
    name: "Recycled Paper Notebooks",
    slug: "recycled-paper-notebooks",
    price: 7.99,
    description: "Eco-friendly notebooks made from 100% recycled paper.",
    fullDescription:
      "Our Recycled Paper Notebooks combine sustainability with functionality. Made from 100% post-consumer recycled paper, these notebooks reduce waste while providing a smooth writing surface. The minimalist design and durable binding make them perfect for work, school, or personal journaling.",
    specifications: [
      "Made from 100% post-consumer recycled paper",
      "80 sheets (160 pages) of lined paper",
      "Cardboard cover made from recycled materials",
      "Binding allows notebook to lay flat when open",
      "Available in various colors",
      "Acid-free paper prevents yellowing over time",
    ],
    image: "/placeholder.svg?height=300&width=300&query=recycled+paper+notebooks",
    images: [
      "/placeholder.svg?height=600&width=600&query=recycled+paper+notebooks",
      "/placeholder.svg?height=600&width=600&query=recycled+paper+notebooks+open",
      "/placeholder.svg?height=600&width=600&query=recycled+paper+notebooks+writing",
      "/placeholder.svg?height=600&width=600&query=recycled+paper+notebooks+set",
    ],
    isNew: false,
    isSale: false,
  },
]
